spring:
  application:
    name: orders-api

  datasource:
    url: jdbc:postgresql://ep-shiny-queen-ayyey6am-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_9db1loKcXSGR
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: shrimp.rmq.cloudamqp.com
    port: 5671
    username: ureohvhj
    password: cbig8rtwyxOVBXnJj_Q7c3ySuxwS6MJW
    virtual-host: ureohvhj
    ssl:
      enabled: true

  data:
    redis:
      host: meet-skylark-108508.upstash.io
      port: 6379
      username: default
      password: gQAAAAAAAafcAAIgcDExNGQyMzU0M2RiNDM0NjBlOWQ3MmQ4M2Q0MjAxY2U4MA
      ssl:
        enabled: true
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.enterprise.orders: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080
